# perl -MDevel::TraceLoad=test
# print STDERR "$Devel::TraceLoad::VERSION\n";

#BEGIN { push @INC, './t' }	
my $ext = '.pl';
require "t/Data/toload$ext";
require 't/Data/toload.pl';
require "t/Data/toload.pl";

eval {
    require Some::Thing; # doesn't exist
    print STDERR "PROBLEM! after     require Some::Thing;\n";
};
print "$@" if $@;
eval {
    require 't/Data/toload'; # doen't exist
    print "PROBLEM! after require 't/Data/toload';\n"
};
print "$@" if $@;
eval {
    require 'nothing'; # doesn't exist
    print "PROBLEM! after require 'nothing';\n"
};
print "$@" if $@;

__END__
Trace generated by t/Data/toload.pl
Can't locate Some/Thing.pm in @INC (@INC contains: C:/Perl/lib C:/Perl/site/lib
.) at t\transparency.pl line 11.
Can't locate t/Data/toload in @INC (@INC contains: C:/Perl/lib C:/Perl/site/lib
.) at t\transparency.pl line 16.
Can't locate nothing in @INC (@INC contains: C:/Perl/lib C:/Perl/site/lib .) at
t\transparency.pl line 21.
